python SurRoL/surrol/data/env_info.py --env NeedleReach-v0
python SurRoL/surrol/data/env_info.py --env NeedlePick-v0
python SurRoL/surrol/data/env_info.py --env GauzeRetrieve-v0 
python SurRoL/surrol/data/env_info.py --env PegTransfer-v0 
python SurRoL/surrol/data/env_info.py --env NeedleRegrasp-v0 
python SurRoL/surrol/data/env_info.py --env BiPegTransfer-v0 
python SurRoL/surrol/data/env_info.py --env ECMReach-v0 
python SurRoL/surrol/data/env_info.py --env MisOrient-v0 
python SurRoL/surrol/data/env_info.py --env StaticTrack-v0 
python SurRoL/surrol/data/env_info.py --env ActiveTrack-v0 
