defaults:
  - agent: sac
  - _self_

# File path
cwd: ${hydra:runtime.output_dir}

# Training params
n_train_steps: 100_001
n_eval: 10
n_save: 5
n_log: 100
num_demo: 100
n_seed_steps: ${agent.n_seed_steps}

replay_buffer_capacity: 100_000
batch_size: 128
device: cuda:3
seed: 1
out_seed: 1
task: NeedleRegrasp-v0
init_task: null
postfix: null
dont_save: False
n_eval_episodes: 20

use_wb: True
project_name: dex2
entity_name: adam-koziak

load_ckpt: False
ckpt_init_dir: ./path/to/ckpt
ckpt_init_episode: latest


# MPI
mpi: {rank: null, is_chef: null, num_workers: null}

# Working space
hydra:
  run:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}/s${seed}
  sweep:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}
    subdir: ${seed}
  sweeper:
    params:
      seed: 1,2,3,4,5
